---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/bosh-gcscli}
inputs:
- name: omg-src-in
outputs:
- name: omg-env-out
run:
  path: omg-src-in/ci/tasks/generate-env.sh