jobs:
  - name: run-unit
    plan:
      - aggregate:
        - {trigger: true, get: omg-src-in, resource: omg-src-in}

      - task: unit-tests
        file: omg-src-in/ci/tasks/run-unit.yml

  - name: prepare-project
    plan:
      - aggregate:
        - {trigger: true, passed: [run-unit], get: omg-src-in, resource: omg-src-in}

      - task: prepare-project
        file: omg-src-in/ci/tasks/prepare-project.yml
        params:
          google_project: {{google_project}}
          google_json_key_data: {{google_json_key_data}}
          google_region: {{google_region}}

  - name: generate-env
    plan:
      - aggregate:
        - {trigger: true, passed: [run-unit], get: omg-src-in, resource: omg-src-in}

      - aggregate: 
        task: generate-env
        file: omg-src-in/ci/tasks/generate-env.yml
        params:
          google_project: {{google_project}}
          google_json_key_data: {{google_json_key_data}}
          google_region: {{google_region}}
          env_file_name: {{env_file_name}}
          env_name: {{env_name}}
          PIVNET_API_TOKEN: {{PIVNET_API_TOKEN}}
          PIVNET_ACCEPT_EULA: {{PIVNET_ACCEPT_EULA}}
          DNS_ZONE_NAME: {{DNS_ZONE_NAME}}
          BASE_IMAGE_URL: {{BASE_IMAGE_URL}}

      - aggregate:
        - put: omg-env-out
          params: {file: omg-env-out/{{env_file_name}}}

resources:
  - name: omg-src-in
    type: git
    source: 
      uri:      {{source_uri}}
      branch:   {{source_branch}}
      username: {{source_username}}
      password: {{source_password}}

  # - name: omg-env-in
  #   type: gcs-resource
  #   source:
  #     bucket: {{ci_bucket_name}}
  #     json_key: {{ci_json_key_date}}
  #     versioned_file: {{env_file_name}}

  - name: omg-env-out
    type: gcs-resource
    source:
      bucket: {{ci_bucket_name}}
      json_key: {{ci_json_key_date}}
      versioned_file: {{env_file_name}}