jobs:
  - name: run-unit
    plan:
      - aggregate:
        - {trigger: true, get: omg-src-in, resource: omg-src-in}

      - task: unit-tests
        file: omg-src-in/ci/tasks/run-unit.yml

  - name: prepare-project
    plan:
      - aggregate:
        - {trigger: true, passed: [run-unit], get: omg-src-in, resource: omg-src-in}

      - task: prepare-project
        file: omg-src-in/ci/tasks/prepare-project.yml
        params:
          google_project: {{google_project}}
          google_json_key_data: {{google_json_key_data}}
          google_region: {{google_region}}

resources:
  - name: omg-src-in
    type: git
    source: 
      uri:      {{source_uri}}
      branch:   {{source_branch}}
      username: {{source_username}}
      password: {{source_password}} 